"""Direct lattice-refinement candidate construction.

This module owns the construction side of sequential lattice design.  A
diagnostic can rank a proposed continuation, but the admissible continuation
should first be generated by the lattice algebra itself.
"""

from dataclasses import dataclass
from itertools import product

import numpy as np

from .lattice_utils import samplecube


@dataclass(frozen=True)
class RefinementCandidateBatch:
    """Candidate points carrying their quotient-coset provenance.

    ``representative`` identifies one element of ``Z^d / K Z^d`` and
    ``offset`` is its image ``G K^{-1} c``.  ``points`` contains the points from
    that coset which lie in the bounded design region used by ``samplecube``.
    An empty point array is retained so boundary exclusion stays visible.
    """

    representative: tuple
    offset: tuple
    points: np.ndarray


def coset_representatives(dilation, tol=1e-9):
    """Return integer representatives for ``Z^d / K Z^d``.

    Parameters
    ----------
    dilation : array-like, shape (d, d)
        Invertible integer dilation matrix ``K``.
    tol : float, optional
        Numerical tolerance used when validating integer input and membership
        in the half-open fundamental parallelepiped.

    Notes
    -----
    The representatives are the integer points in ``K [0,1)^d``.  Their count
    is ``abs(det K)``, the refinement index of the nested lattice.
    """
    K, index = _as_integer_dilation(dilation, tol=tol)
    dim = K.shape[0]
    invK = np.linalg.inv(K.astype(float))

    corners = np.array(list(product([0.0, 1.0], repeat=dim)), dtype=float).T
    vertices = (K.astype(float) @ corners).T
    lower = np.floor(np.min(vertices, axis=0) - tol).astype(int)
    upper = np.ceil(np.max(vertices, axis=0) + tol).astype(int)

    reps = []
    for candidate in product(
        *[range(int(lower[j]), int(upper[j]) + 1) for j in range(dim)]
    ):
        vector = np.asarray(candidate, dtype=int)
        coordinates = invK @ vector.astype(float)
        if _in_half_open_unit_cube(coordinates, tol=tol):
            reps.append(vector)

    reps = _sort_representatives(reps)
    if len(reps) != index:
        raise ValueError(
            "failed to enumerate the expected number of coset representatives: "
            f"found {len(reps)}, expected {index}"
        )
    if not _representatives_are_distinct(reps, invK, tol=tol):
        raise ValueError("enumerated representatives are not distinct modulo K Z^d")
    return np.asarray(reps, dtype=int)


def refinement_offsets(basis, dilation, include_base=False, tol=1e-9):
    """Return coset offsets ``G K^{-1} c`` for one refinement step.

    ``include_base=False`` omits the zero coset, so the result contains only
    new refinement layers relative to the coarse lattice ``G Z^d``.
    """
    G = _as_square_matrix(basis, "basis")
    K, _ = _as_integer_dilation(dilation, dim=G.shape[0], tol=tol)
    reps = coset_representatives(K, tol=tol)
    invK = np.linalg.inv(K.astype(float))

    rows = []
    for representative in reps:
        if not include_base and np.all(representative == 0):
            continue
        rows.append(G @ invK @ representative.astype(float))
    if not rows:
        return np.empty((0, G.shape[0]), dtype=float)
    return np.asarray(rows, dtype=float)


def refinement_candidate_points(
    basis,
    dilation,
    xofs=None,
    eps=1e-6,
    epsdirub=1,
    include_base=False,
    tol=1e-9,
):
    """Generate unit-cube candidate points from a one-step lattice refinement.

    The refined lattice decomposes as

    ``G K^{-1} Z^d = union_c (G Z^d + G K^{-1} c)``,

    where ``c`` ranges over representatives of ``Z^d / K Z^d``.  This function
    samples each non-zero coset offset inside the unit cube and returns the
    unique admitted points.
    """
    G = _as_square_matrix(basis, "basis")
    batches = refinement_candidate_batches(
        G,
        dilation,
        xofs=xofs,
        eps=eps,
        epsdirub=epsdirub,
        include_base=include_base,
        tol=tol,
    )
    chunks = [batch.points for batch in batches if batch.points.size]
    if not chunks:
        return np.empty((0, G.shape[0]), dtype=float)
    return _unique_points(np.vstack(chunks), tol=tol)


def refinement_candidate_batches(
    basis,
    dilation,
    xofs=None,
    eps=1e-6,
    epsdirub=1,
    include_base=False,
    tol=1e-9,
):
    """Generate one bounded candidate batch per quotient representative.

    Unlike :func:`refinement_candidate_points`, this function does not flatten
    the refinement shell.  It retains the representative and offset for every
    coset, including a coset whose translated lattice has no point in the
    bounded region.  This provenance is needed to distinguish a complete
    refinement shell, a coset batch, and an ordered within-shell prefix.
    """
    G = _as_square_matrix(basis, "basis")
    K, _ = _as_integer_dilation(dilation, dim=G.shape[0], tol=tol)
    xofs = _as_offset(xofs, G.shape[0])
    invK = np.linalg.inv(K.astype(float))

    batches = []
    for representative in coset_representatives(K, tol=tol):
        if not include_base and np.all(representative == 0):
            continue
        offset = G @ invK @ representative.astype(float)
        points = samplecube(G, xofs=xofs + offset, eps=eps, epsdirub=epsdirub)
        if points.size:
            points = _unique_points(points, tol=tol)
        else:
            points = np.empty((0, G.shape[0]), dtype=float)
        batches.append(
            RefinementCandidateBatch(
                representative=tuple(int(value) for value in representative),
                offset=tuple(float(value) for value in offset),
                points=points,
            )
        )
    return batches


def _as_integer_dilation(dilation, dim=None, tol=1e-9):
    K_float = _as_square_matrix(dilation, "dilation")
    if dim is not None and K_float.shape != (dim, dim):
        raise ValueError("dilation must have the same dimension as basis.")
    K = np.rint(K_float).astype(int)
    if not np.allclose(K_float, K, atol=tol, rtol=0.0):
        raise ValueError("dilation must have integer entries.")
    det = int(round(np.linalg.det(K.astype(float))))
    index = abs(det)
    if index < 1:
        raise ValueError("dilation must be invertible.")
    return K, index


def _as_square_matrix(matrix, name):
    out = np.asarray(matrix, dtype=float)
    if out.ndim != 2 or out.shape[0] != out.shape[1]:
        raise ValueError(f"{name} must be a square matrix.")
    return out


def _as_offset(xofs, dim):
    if xofs is None:
        return np.zeros(dim, dtype=float)
    out = np.asarray(xofs, dtype=float)
    if out.shape != (dim,):
        raise ValueError("xofs must have shape (dimension,).")
    return out


def _in_half_open_unit_cube(coordinates, tol):
    return bool(
        np.all(coordinates >= -tol)
        and np.all(coordinates < 1.0 - tol)
    )


def _sort_representatives(reps):
    return sorted(
        reps,
        key=lambda vector: (
            float(np.dot(vector, vector)),
            tuple(int(x) for x in vector),
        ),
    )


def _representatives_are_distinct(reps, invK, tol):
    for i, left in enumerate(reps):
        for right in reps[i + 1 :]:
            coordinates = invK @ (left.astype(float) - right.astype(float))
            if np.allclose(coordinates, np.rint(coordinates), atol=tol, rtol=0.0):
                return False
    return True


def _unique_points(points, tol):
    rounded = np.round(points / tol).astype(np.int64)
    _, unique_indices = np.unique(rounded, axis=0, return_index=True)
    unique = points[np.sort(unique_indices)]
    unique[np.isclose(unique, 0.0, atol=tol)] = 0.0
    unique[np.isclose(unique, 1.0, atol=tol)] = 1.0
    return unique
